package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ksfc.newfarmer.beans.dbbeans.PotentialCustomersEntity;
import com.ksfc.newfarmer.beans.dbbeans.InviteeEntity;
import com.ksfc.newfarmer.beans.dbbeans.OfflineShoppingCart;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig potentialCustomersEntityDaoConfig;
    private final DaoConfig inviteeEntityDaoConfig;
    private final DaoConfig offlineShoppingCartDaoConfig;

    private final PotentialCustomersEntityDao potentialCustomersEntityDao;
    private final InviteeEntityDao inviteeEntityDao;
    private final OfflineShoppingCartDao offlineShoppingCartDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        potentialCustomersEntityDaoConfig = daoConfigMap.get(PotentialCustomersEntityDao.class).clone();
        potentialCustomersEntityDaoConfig.initIdentityScope(type);

        inviteeEntityDaoConfig = daoConfigMap.get(InviteeEntityDao.class).clone();
        inviteeEntityDaoConfig.initIdentityScope(type);

        offlineShoppingCartDaoConfig = daoConfigMap.get(OfflineShoppingCartDao.class).clone();
        offlineShoppingCartDaoConfig.initIdentityScope(type);

        potentialCustomersEntityDao = new PotentialCustomersEntityDao(potentialCustomersEntityDaoConfig, this);
        inviteeEntityDao = new InviteeEntityDao(inviteeEntityDaoConfig, this);
        offlineShoppingCartDao = new OfflineShoppingCartDao(offlineShoppingCartDaoConfig, this);

        registerDao(PotentialCustomersEntity.class, potentialCustomersEntityDao);
        registerDao(InviteeEntity.class, inviteeEntityDao);
        registerDao(OfflineShoppingCart.class, offlineShoppingCartDao);
    }
    
    public void clear() {
        potentialCustomersEntityDaoConfig.getIdentityScope().clear();
        inviteeEntityDaoConfig.getIdentityScope().clear();
        offlineShoppingCartDaoConfig.getIdentityScope().clear();
    }

    public PotentialCustomersEntityDao getPotentialCustomersEntityDao() {
        return potentialCustomersEntityDao;
    }

    public InviteeEntityDao getInviteeEntityDao() {
        return inviteeEntityDao;
    }

    public OfflineShoppingCartDao getOfflineShoppingCartDao() {
        return offlineShoppingCartDao;
    }

}
